// ============================================
// DATA SERVICE - ABSTRACTION LAYER
// ============================================
// This file routes data requests to either mock data or Supabase
// DO NOT EDIT THIS FILE (neither in GitHub nor Figma Make)
// It automatically switches based on USE_SUPABASE flag in config.ts

import { USE_SUPABASE } from './config';
import { mockPeerSupportData, mockActivities, mockResourceCategories } from '../data/mockData';
import * as supabaseApi from './supabase';
import type { PeerSupportItem, Activity, ResourceCategory } from './types';

// ============================================
// PEER SUPPORT DATA SERVICE
// ============================================

export async function getPeerSupportData(): Promise<PeerSupportItem[]> {
  if (USE_SUPABASE) {
    return await supabaseApi.fetchPeerSupportData();
  }
  return Promise.resolve(mockPeerSupportData);
}

export async function addPeerSupportItem(item: Omit<PeerSupportItem, 'id'>): Promise<PeerSupportItem> {
  if (USE_SUPABASE) {
    return await supabaseApi.createPeerSupportItem(item);
  }
  // For mock data, just return with generated ID
  const newItem = { ...item, id: `temp-${Date.now()}` };
  return Promise.resolve(newItem);
}

export async function editPeerSupportItem(id: string, updates: Partial<PeerSupportItem>): Promise<PeerSupportItem> {
  if (USE_SUPABASE) {
    return await supabaseApi.updatePeerSupportItem(id, updates);
  }
  // For mock data, find and return updated item
  const item = mockPeerSupportData.find(i => i.id === id);
  if (!item) throw new Error('Item not found');
  return Promise.resolve({ ...item, ...updates });
}

export async function removePeerSupportItem(id: string): Promise<void> {
  if (USE_SUPABASE) {
    return await supabaseApi.deletePeerSupportItem(id);
  }
  return Promise.resolve();
}

// ============================================
// ACTIVITIES DATA SERVICE
// ============================================

export async function getActivities(): Promise<Activity[]> {
  if (USE_SUPABASE) {
    return await supabaseApi.fetchActivities();
  }
  return Promise.resolve(mockActivities);
}

export async function addActivity(activity: Omit<Activity, 'id'>): Promise<Activity> {
  if (USE_SUPABASE) {
    return await supabaseApi.createActivity(activity);
  }
  const newActivity = { ...activity, id: `temp-${Date.now()}` };
  return Promise.resolve(newActivity);
}

export async function editActivity(id: string, updates: Partial<Activity>): Promise<Activity> {
  if (USE_SUPABASE) {
    return await supabaseApi.updateActivity(id, updates);
  }
  const activity = mockActivities.find(a => a.id === id);
  if (!activity) throw new Error('Activity not found');
  return Promise.resolve({ ...activity, ...updates });
}

export async function removeActivity(id: string): Promise<void> {
  if (USE_SUPABASE) {
    return await supabaseApi.deleteActivity(id);
  }
  return Promise.resolve();
}

// ============================================
// RESOURCES DATA SERVICE
// ============================================

export async function getResourceCategories(): Promise<ResourceCategory[]> {
  if (USE_SUPABASE) {
    return await supabaseApi.fetchResourceCategories();
  }
  return Promise.resolve(mockResourceCategories);
}

export async function addResourceCategory(category: Omit<ResourceCategory, 'id'>): Promise<ResourceCategory> {
  if (USE_SUPABASE) {
    return await supabaseApi.createResourceCategory(category);
  }
  const newCategory = { ...category, id: `temp-${Date.now()}` };
  return Promise.resolve(newCategory);
}

export async function editResourceCategory(id: string, updates: Partial<ResourceCategory>): Promise<ResourceCategory> {
  if (USE_SUPABASE) {
    return await supabaseApi.updateResourceCategory(id, updates);
  }
  const category = mockResourceCategories.find(c => c.id === id);
  if (!category) throw new Error('Category not found');
  return Promise.resolve({ ...category, ...updates });
}

export async function removeResourceCategory(id: string): Promise<void> {
  if (USE_SUPABASE) {
    return await supabaseApi.deleteResourceCategory(id);
  }
  return Promise.resolve();
}
