// ============================================
// DATA SERVICE - ABSTRACTION LAYER
// ============================================
// This file routes data requests to either mock data or Supabase
// DO NOT EDIT THIS FILE (neither in GitHub nor Figma Make)
// It automatically switches based on USE_SUPABASE flag in config.ts

import { USE_SUPABASE } from './config';
import * as supabaseApi from './supabase';
import type { PeerSupportItem, Activity, ResourceCategory, StudentDocument, DriveSyncRecord } from './types';
import type { Generation, Board, BoardContent, KeywordConfig } from './types';
// ============================================
// PEER SUPPORT DATA SERVICE
// ============================================

export async function getPeerSupportData(): Promise<PeerSupportItem[]> {
  if (USE_SUPABASE) {
    return await supabaseApi.fetchPeerSupportData();
  }
  return [];
}

export async function getStudentDocuments(filters?: { years?: number[], blocks?: string[] }): Promise<StudentDocument[]> {
  if (USE_SUPABASE) {
    return await supabaseApi.fetchStudentDocuments(filters);
  }
  return [];
}

export async function addPeerSupportItem(item: Omit<PeerSupportItem, 'id'>): Promise<PeerSupportItem> {
  if (USE_SUPABASE) {
    return await supabaseApi.createPeerSupportItem(item);
  }
  throw new Error('Supabase not enabled');
}

export async function editPeerSupportItem(id: string, updates: Partial<PeerSupportItem>): Promise<PeerSupportItem> {
  if (USE_SUPABASE) {
    return await supabaseApi.updatePeerSupportItem(id, updates);
  }
  throw new Error('Supabase not enabled');
}

export async function removePeerSupportItem(id: string): Promise<void> {
  if (USE_SUPABASE) {
    return await supabaseApi.deletePeerSupportItem(id);
  }
}

export async function createStudentDocument(
  record: Partial<StudentDocument>
): Promise<StudentDocument> {
  if (USE_SUPABASE) {
    return await supabaseApi.createStudentDocument(record);
  }
  throw new Error('Supabase not enabled');
}

export function extractDriveId(url: string): string | null {
  return supabaseApi.extractDriveId(url);
}

export async function updateStudentDocument(id: number, updates: Partial<StudentDocument>): Promise<StudentDocument> {
  if (USE_SUPABASE) {
    return await supabaseApi.updateStudentDocument(id, updates);
  }
  throw new Error('Supabase not enabled');
}

export async function deleteStudentDocument(id: number): Promise<void> {
  if (USE_SUPABASE) {
    return await supabaseApi.deleteStudentDocument(id);
  }
  throw new Error('Supabase not enabled');
}

// ============================================
// ACTIVITIES DATA SERVICE
// ============================================

export async function getActivities(): Promise<Activity[]> {
  if (USE_SUPABASE) {
    return await supabaseApi.fetchActivities();
  }
  return [];
}

export async function addActivity(activity: Omit<Activity, 'id'>): Promise<Activity> {
  if (USE_SUPABASE) {
    return await supabaseApi.createActivity(activity);
  }
  throw new Error('Supabase not enabled');
}

export async function editActivity(id: string, updates: Partial<Activity>): Promise<Activity> {
  if (USE_SUPABASE) {
    return await supabaseApi.updateActivity(id, updates);
  }
  throw new Error('Supabase not enabled');
}

export async function removeActivity(id: string): Promise<void> {
  if (USE_SUPABASE) {
    return await supabaseApi.deleteActivity(id);
  }
}

// ============================================
// RESOURCES DATA SERVICE
// ============================================

export async function getResourceCategories(): Promise<ResourceCategory[]> {
  if (USE_SUPABASE) {
    return await supabaseApi.fetchResourceCategories();
  }
  return [];
}

export async function addResourceCategory(
  category: { title: string; description: string; icon: string; link: string; items?: { name: string; type: string }[] }
): Promise<ResourceCategory> {
  if (USE_SUPABASE) {
    return await supabaseApi.createResourceCategory(category);
  }
  throw new Error('Supabase not enabled');
}

export async function editResourceCategory(
  id: string,
  updates: { id?: string; title?: string; description?: string; icon?: string; link?: string; items?: { name: string; type: string }[] }
): Promise<ResourceCategory> {
  if (USE_SUPABASE) {
    return await supabaseApi.updateResourceCategory(id, updates);
  }
  throw new Error('Supabase not enabled');
}

export async function removeResourceCategory(id: string): Promise<void> {
  if (USE_SUPABASE) {
    return await supabaseApi.deleteResourceCategory(id);
  }
}

// ============================================
// GENERATIONS
// ============================================

export async function getGenerations(): Promise<Generation[]> {
  if (USE_SUPABASE) return await supabaseApi.fetchGenerations();
  return [];
}

export async function addGeneration(
  gen: Omit<Generation, 'id' | 'created_at'>
): Promise<Generation> {
  if (USE_SUPABASE) return await supabaseApi.createGeneration(gen);
  throw new Error('Supabase not enabled');
}

export async function editGeneration(
  id: string,
  updates: Partial<Generation>
): Promise<Generation> {
  if (USE_SUPABASE) return await supabaseApi.updateGeneration(id, updates);
  throw new Error('Supabase not enabled');
}

export async function removeGeneration(id: string): Promise<void> {
  if (USE_SUPABASE) return await supabaseApi.deleteGeneration(id);
}

// ============================================
// BOARDS
// ============================================

export async function getBoards(generationId: string): Promise<Board[]> {
  if (USE_SUPABASE) return await supabaseApi.fetchBoardsByGeneration(generationId);
  return [];
}

export async function addBoard(
  board: Omit<Board, 'id' | 'created_at' | 'updated_at'>
): Promise<Board> {
  if (USE_SUPABASE) return await supabaseApi.createBoard(board);
  throw new Error('Supabase not enabled');
}

export async function editBoard(
  id: string,
  updates: Partial<Board>
): Promise<Board> {
  if (USE_SUPABASE) return await supabaseApi.updateBoard(id, updates);
  throw new Error('Supabase not enabled');
}

export async function removeBoard(id: string): Promise<void> {
  if (USE_SUPABASE) return await supabaseApi.deleteBoard(id);
}

// ============================================
// BOARD CONTENT
// ============================================

export async function getBoardContent(
  boardId: string
): Promise<BoardContent | null> {
  if (USE_SUPABASE) return await supabaseApi.fetchBoardContent(boardId);
  return null;
}

export async function saveBoardContentData(
  boardId: string,
  content: object
): Promise<void> {
  if (USE_SUPABASE) return await supabaseApi.saveBoardContent(boardId, content);
}

// ============================================
// KEYWORD CONFIGURATIONS
// ============================================

export async function getKeywordConfigs(): Promise<KeywordConfig[]> {
  if (USE_SUPABASE) {
    return await supabaseApi.fetchKeywordConfigs();
  }
  return [];
}

export async function addKeywordConfig(config: Omit<KeywordConfig, 'id'>): Promise<KeywordConfig> {
  if (USE_SUPABASE) {
    return await supabaseApi.createKeywordConfig(config);
  }
  throw new Error('Supabase not enabled');
}

export async function editKeywordConfig(id: string, updates: Partial<KeywordConfig>): Promise<KeywordConfig> {
  if (USE_SUPABASE) {
    return await supabaseApi.updateKeywordConfig(id, updates);
  }
  throw new Error('Supabase not enabled');
}

export async function removeKeywordConfig(id: string): Promise<void> {
  if (USE_SUPABASE) {
    await supabaseApi.deleteKeywordConfig(id);
  }
}

// ============================================
// DriveSyncRecord
// ============================================

export async function getDriveSync(): Promise<DriveSyncRecord[]> {
  if (USE_SUPABASE) {
    return await supabaseApi.fetchDriveSync();
  }
  return [];
}
 
export async function upsertStudentDocuments(
  records: Partial<import('./types').StudentDocument>[]
): Promise<void> {
  if (USE_SUPABASE) {
    return await supabaseApi.upsertStudentDocuments(records);
  }
}

// ============================================
// User Preferences
// ============================================

export async function getUserPreference(email: string): Promise<string | null> {
  if (USE_SUPABASE) {
    return await supabaseApi.fetchUserPreference(email);
  }
  return null;
}

export async function saveUserPreference(email: string, year: string): Promise<void> {
  if (USE_SUPABASE) {
    return await supabaseApi.upsertUserPreference(email, year);
  }
}

export async function runAdminUpgradeYear(): Promise<void> {
  if (USE_SUPABASE) {
    return await supabaseApi.adminUpgradeYearOneToTwo();
  }
}